services:
    php:
        container_name: "${APP_NAME}-php"
        build: .docker
        image: app
        depends_on:
            - mysql
        volumes:
            - ./:/var/www/html
            - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        restart: always
        env_file:
            - ./.env
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - PHP_IDE_CONFIG=serverName=XdebugServer
            - DEBUG=1
        networks:
            - flight

    flight.app:
        container_name: "${APP_NAME}-nginx"
        image: nginx:alpine
        ports:
            - "9899:80"
        volumes:
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/nginx/:/var/log/nginx/
        depends_on:
            - php
        restart: always
        env_file:
            - ./.env
        networks:
            - flight

    mysql:
        container_name: "${APP_NAME}-mysql"
        image: mysql:5.7.22
        ports:
            - "${DB_PORT:-3306}:3306"
        volumes:
            - /mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
        env_file:
            - ./.env
        networks:
            - flight

networks:
    flight:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
